package:
    type:           yii2-extension
    name:           yii2-asset-pictonic
    title:          Yii2 asset for Pictonic
    keywords:       pictonic, asset, extension, yii2
    namespace:      hiqdev\assets\pictonic
    description:    Yii2 asset for https://pictonic.co/free

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
